#!/usr/bin/env python
# -*- coding: utf-8 -*-

from turtle import turtlesize
import rospy, roslaunch, os
from enum import Enum
from std_msgs.msg import UInt8
 
class CoreNodeController():
    def __init__(self):
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('core/nodes', '')

        # Subscriber
        self.sub_mission = rospy.Subscriber('/mission', UInt8, self.cbReceiveMode, queue_size=1)

        # Sub from each mission step data
        # example
        # rospy.Subscriber('/mission/intersection', UInt8, self.cbIntersectionStep, queue_size=1)
        rospy.Subscriber('/mission/turtlesim', UInt8, self.cbTurtleStep, queue_size=1)

        # self.Mission = Enum('Mission', 'Idle TrafficLight Intersection Construction Parking LevelCrossing Tunnel')
        self.Mission = Enum('Mission', 'Idle, OpenTurtleSim CloseTurtleSim')

        # each mission step enum
        # self.IntersectionStep = Enum('IntersectionStep', 'default process')
        self.TurtlesimStep = Enum('TurtlesimStep', 'turtlesim turtleteleop')

        self.is_triggered = False
        self.current_mode = self.Mission.Idle.value
        # self.current_step_intersection = self.IntersectionStep.default.value
        self.current_setp_turtlesim = self.TurtlesimStep.turtlesim.value

        # launcher enum
        self.Launcher = Enum('Launcher', 'turtlesim turtleteleop')
        self.launch_turtlesim_launched = False
        self.launch_turtleteleop_launched = False


        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
        
        loop_rate = rospy.Rate(10) # 10hz

        while not rospy.is_shutdown():
            if self.is_triggered == True:
                self.fnControlNode()
            
            loop_rate.sleep()

    def cbReceiveMode(self, mode_msg):
        rospy.loginfo("starts the progress with %d", mode_msg.data)
        
        self.current_mode = mode_msg.data
        self.is_triggered = True

    # create callback function
    # example
    # def cbIntersectionStep(self, mode_msg):
    #     self.current_step_intersection = mode_msg.data
    #     self.is_triggered = True

    def cbTurtleStep(self, mode_msg):
        self.current_setp_turtlesim = mode_msg.data
        self.is_triggered = True

    def fnControlNode(self):

        # example
        if self.current_mode == self.Mission.OpenTurtleSim.value:

            if self.current_setp_turtlesim == self.TurtlesimStep.turtlesim.value:
                rospy.loginfo("OPEN TURTLESIM")
                self.fnLaunch(self.Launcher.turtlesim.value, True)

            elif self.current_setp_turtlesim == self.TurtlesimStep.turtleteleop.value:
                rospy.loginfo("OPEN TURTLE_TELEOP")
                self.fnLaunch(self.Launcher.turtleteleop.value, True)

        elif self.current_mode == self.Mission.CloseTurtleSim.value:
            rospy.loginfo("CLOSE TURTLESIM")
            self.fnLaunch(self.Launcher.turtlesim.value, False)
            self.fnLaunch(self.Launcher.turtlesim.value, False)
            self.current_setp_turtlesim = self.TurtlesimStep.turtlesim.value

                    
        self.is_triggered = False

    def fnLaunch(self, launch_num, is_start):

        # example 
        if launch_num == self.Launcher.turtlesim.value:
            if is_start == True:
                if self.launch_turtlesim_launched == False:
                    self.launch_turtlesim = roslaunch.scriptapi.ROSLaunch()
                    self.launch_turtlesim = roslaunch.parent.ROSLaunchParent(self.uuid, [self.ros_package_path + "core/launch/turtlesim.launch"])
                    self.launch_turtlesim_launched = True
                    self.launch_turtlesim.start()
                else:
                    pass
            else:
                if self.launch_turtlesim_launched == True:
                    self.launch_turtlesim_launched = False
                    self.launch_turtlesim.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.turtleteleop.value:
            if is_start == True:
                if self.launch_turtleteleop_launched == False:
                    self.launch_turtleteleop = roslaunch.scriptapi.ROSLaunch()
                    self.launch_turtleteleop = roslaunch.parent.ROSLaunchParent(self.uuid, [self.ros_package_path + "core/launch/turtle_teleop_key.launch"])
                    self.launch_turtleteleop_launched = True
                    self.launch_turtleteleop.start()
                else:
                    pass
            else:
                if self.launch_turtleteleop_launched == True:
                    self.launch_turtleteleop_launched = False
                    self.launch_turtleteleop.shutdown()
                else:
                    pass
            
    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('core_node_controller')
    node = CoreNodeController()
    node.main()
